export const defaultDict = {
	"dictionaryForm": {
		"abgeschaut": "abschauen",
		"ahnen": "ahnen",
		"allernächsten": "allernächsten",
		"angepasst": "anpassen",
		"anspruch": "anspruch",
		"art": "die Art",
		"aufbau": "der Aufbau",
		"ausgrabungen": "die Ausgrabung",
		"auswanderergruppen": "die Gruppe",
		"beschleunigte": "beschleunigen",
		"bestgehüteten": "hüten",
		"bestimmte": "bestimmt",
		"bewahrt": "bewahrt",
		"bezeichnen": "bezeichnen",
		"dreinblickenden": "dreinblicken",
		"ebenfalls": "ebenfalls",
		"eigenschaften": "die Eigenschaft",
		"eingestellt": "einstellen",
		"entstanden": "entstehen",
		"entwickelten": "entwickeln",
		"entwicklung": "die Entwicklung",
		"ereignis": "das Ereignis",
		"erfanden": "erfinden",
		"ergaben": "ergeben",
		"ergebnis": "das Ergebnis",
		"erheblich": "erheblich",
		"feige": "feig",
		"fortpflanzung": "die Fortpflanzung",
		"fortpflanzungsfähige": "fortpflanzungsfähig",
		"fähigkeiten": "die Fähigkeit",
		"gattung": "die Gattung",
		"gattungen": "die Gattung",
		"gefletschten": "fletschen",
		"gehütet": "hüten",
		"geprägt": "prägen",
		"geräusch": "das Geräusch",
		"geschichte": "die Geschichte",
		"getauft": "taufen",
		"gewisse": "gewiss",
		"grundlegenden": "grundlegend",
		"hervorging": "hervorgehen",
		"hochtrabend": "hochtrabend",
		"jedoch": "jedoch",
		"katzenvorfahren": "der Vorfahre",
		"keller": "der Keller",
		"knurrend": "knurren",
		"krawalligen": "krawallen",
		"lebewesen": "das Lebenswesen",
		"leichen": "die Leiche",
		"libellen": "die Libelle",
		"matsch": "der Matsch",
		"maultiere": "der Maultier",
		"menschenaffen": "der Menschenaffe",
		"menschenähnlichen": "menschenähnlich",
		"menschheit": "die Menschheit",
		"mitlebewesen": "das Mitlebewesen",
		"nachwuchs": "der Nachwuchs",
		"namens": "namens",
		"quallen": "die Qualle",
		"reihe": "die Reihe",
		"richtungen": "die Richtung",
		"salopp": "salopp",
		"scheinbar": "scheinbar",
		"schwülen": "schwül",
		"spalten": "spalten",
		"speerschwingenden": "schwingen",
		"stachen": "stechen",
		"stießen": "stoßen",
		"streift": "streifen",
		"stritten": "streiten",
		"trubel": "der Trubel",
		"unauffällige": "unauffällig",
		"unauffälliges": "unauffällig",
		"unfruchtbar": "unfruchtbar",
		"urahn": "der Urahn",
		"urahnin": "die Urahnin",
		"urknall": "der Urknall",
		"verbanden": "verbinden",
		"vermutlich": "vermutlich",
		"verschneiten": "schneien",
		"versteinerten": "versteinert",
		"verwandten": "verwanden",
		"vettern": "der Vetter",
		"vielzahl": "die Vielzahl",
		"vorfahren": "der Vorfahre",
		"vormachtstellung": "die Vormachtstellung",
		"waisenkind": "das Waisenkind",
		"werkzeugherstellung": "die Herstellung",
		"wiederum": "wiederum",
		"währenddessen": "währenddessen",
		"zahmsten": "zahm",
		"zeugen": "zeugen",
		"zogen": "ziehen",
		"zusammenschlossen": "schließen",
		"zweiteilige": "zweiteilig",
		"äußerlich": "äußerlich"
	},
	"en": {
		"abgeschaut": "peep, copied",
		"ahnen": "suspect",
		"allernächsten": "very next",
		"angepasst": "adapted",
		"anspruch": "claim",
		"art": "kind",
		"aufbau": "building",
		"ausgrabungen": "excavations",
		"auswanderergruppen": "emigrant groups",
		"beschleunigte": "sped up",
		"bestgehüteten": "best-kept",
		"bestimmte": "certain",
		"bewahrt": "preserved",
		"bezeichnen": "describe",
		"dreinblickenden": "looking",
		"ebenfalls": "likewise",
		"eigenschaften": "properties",
		"eingestellt": "adjusted",
		"entstanden": "emerged",
		"entwickelten": "developed",
		"entwicklung": "development",
		"ereignis": "event",
		"erfanden": "invent",
		"ergaben": "resulted",
		"ergebnis": "result",
		"erheblich": "considerable",
		"feige": "cowardly",
		"fortpflanzung": "reproduction",
		"fortpflanzungsfähige": "reproductive-able",
		"fähigkeiten": "skills",
		"gattung": "genus",
		"gattungen": "genera",
		"gefletschten": "bared",
		"gehütet": "protected",
		"geprägt": "embossed, shaped, formed",
		"geräusch": "noise",
		"geschichte": "history",
		"getauft": "baptized",
		"gewisse": "certain",
		"grundlegenden": "fundamental",
		"hervorging": "emerged",
		"hochtrabend": "grandiose, pompous",
		"jedoch": "however",
		"katzenvorfahren": "cat ansectors",
		"keller": "cellar",
		"knurrend": "growling",
		"krawalligen": "rowdy",
		"lebewesen": "lifeform",
		"leichen": "corpses",
		"libellen": "dragonflies",
		"matsch": "mud; passion",
		"maultiere": "mules",
		"menschenaffen": "great apes",
		"menschenähnlichen": "humanlike",
		"menschheit": "humankind",
		"mitlebewesen": "fellow creatures",
		"nachwuchs": "offsprings",
		"namens": "called",
		"quallen": "jellyfish",
		"reihe": "row",
		"richtungen": "directions",
		"salopp": "casually, slangy",
		"scheinbar": "seemingly",
		"schwülen": "sultry",
		"spalten": "split",
		"speerschwingenden": "spear-wielding",
		"stachen": "stung",
		"stießen": "bumped",
		"streift": "walks",
		"stritten": "argued",
		"trubel": "hustle",
		"unauffällige": "unremarkable",
		"unauffälliges": "unremarkable",
		"unfruchtbar": "barren",
		"urahn": "ancestor",
		"urahnin": "ancestral mother",
		"urknall": "Big Bang",
		"verbanden": "bond",
		"vermutlich": "allegedly, presumably",
		"verschneiten": "snowy",
		"versteinerten": "petrified",
		"verwandten": "relatives",
		"vettern": "cousins",
		"vielzahl": "variety",
		"vorfahren": "ancestors",
		"vormachtstellung": "supremacy",
		"waisenkind": "orphan",
		"werkzeugherstellung": "instrument creation",
		"wiederum": "in turn",
		"währenddessen": "meanwhile",
		"zahmsten": "tamest",
		"zeugen": "testify; beget",
		"zogen": "pulled",
		"zusammenschlossen": "united",
		"zweiteilige": "two-part",
		"äußerlich": "externally"
	},
	"ru": {
		"abgeschaut": "подглядел, скопировал",
		"ahnen": "подозревать",
		"allernächsten": "самые ближние; совсем рядом",
		"angepasst": "адаптировавшийся",
		"anspruch": "притязание, претензия",
		"art": "вид",
		"aufbau": "строительство",
		"ausgrabungen": "раскопки",
		"auswanderergruppen": "группы переселенцев",
		"beschleunigte": "ускорил",
		"bestgehüteten": "наиболее оберегаемый",
		"bestimmte": "определённая",
		"bewahrt": "сохранён",
		"bezeichnen": "описывать",
		"dreinblickenden": "смотрящий",
		"ebenfalls": "также, равным образом",
		"eigenschaften": "характеристики",
		"eingestellt": "приспособленный",
		"entstanden": "появились",
		"entwickelten": "развили",
		"entwicklung": "развитие",
		"ereignis": "событие",
		"erfanden": "изобретали",
		"ergaben": "дали результат",
		"ergebnis": "результат",
		"erheblich": "значительно",
		"feige": "трусливые",
		"fortpflanzung": "размножение",
		"fortpflanzungsfähige": "плодородные",
		"fähigkeiten": "навыки",
		"gattung": "род",
		"gattungen": "рода",
		"gefletschten": "обнажённый",
		"gehütet": "сберёг",
		"geprägt": "сформированный",
		"geräusch": "шум",
		"geschichte": "история",
		"getauft": "окрещён",
		"gewisse": "определённая",
		"grundlegenden": "основополагающий",
		"hervorging": "появился",
		"hochtrabend": "грандиозный, помпезный",
		"jedoch": "тем не менее",
		"katzenvorfahren": "предки кошек",
		"keller": "погреб",
		"knurrend": "рычащий",
		"krawalligen": "хулиганистые",
		"lebewesen": "форма жизни",
		"leichen": "трупы",
		"libellen": "стрекозы",
		"matsch": "грязь; азарт",
		"maultiere": "мулы",
		"menschenaffen": "человекоподобные обезьяны",
		"menschenähnlichen": "человекоподобные",
		"menschheit": "человечество",
		"mitlebewesen": "братья наши меньшие",
		"nachwuchs": "потомки",
		"namens": "под названием",
		"quallen": "медузы",
		"reihe": "ряд",
		"richtungen": "направления",
		"salopp": "небрежно, грубовато",
		"scheinbar": "кажущийся, по-видимому",
		"schwülen": "знойный",
		"spalten": "расщеплять",
		"speerschwingenden": "вооружённые копьями",
		"stachen": "ужалили",
		"stießen": "наткнулись",
		"streift": "прогуливается",
		"stritten": "спорили",
		"trubel": "суета",
		"unauffällige": "непримечательный",
		"unauffälliges": "неприметный",
		"unfruchtbar": "бесплодный",
		"urahn": "предок",
		"urahnin": "прародительница",
		"urknall": "Большой Взрыв",
		"verbanden": "связали",
		"vermutlich": "якобы, предположительно",
		"verschneiten": "заснеженный",
		"versteinerten": "окаменелые",
		"verwandten": "родственники",
		"vettern": "кузены",
		"vielzahl": "разнообразие",
		"vorfahren": "предки",
		"vormachtstellung": "превосходство",
		"waisenkind": "сирота",
		"werkzeugherstellung": "создание инструментов",
		"wiederum": "в свою очередь",
		"währenddessen": "тем временем",
		"zahmsten": "наиболее приручённый",
		"zeugen": "свидетельствовать; зачинать",
		"zogen": "тянули",
		"zusammenschlossen": "соединились",
		"zweiteilige": "двухчастный",
		"äußerlich": "внешне"
	}
}

export default defaultDict
