const defaultDict = {
	"en": {
	  "urknall": "Big Bang",
	  "verbanden": "bond",
	  "namens": "called",
	  "entstanden": "emerged",
	  "ereignis": "event",
	  "grundlegenden": "fundamental",
	  "eigenschaften": "properties",
	  "wiederum": "in turn",
	  "zusammenschlossen": "united",
	  "bestimmte": "certain",
	  "bezeichnen": "describe",
	  "aufbau": "building",
	  "entwicklung": "development",
	  "geprägt": "embossed, shaped, formed",
	  "beschleunigte": "sped up",
	  "mitlebewesen": "fellow creatures",
	  "menschenähnlichen": "humanlike",
	  "stachen": "stung",
	  "vielzahl": "variety",
	  "vermutlich": "allegedly, presumably",
	  "äußerlich": "externally",
	  "gewisse": "certain",
	  "matsch": "mud; passion",
	  "geräusch": "noise",
	  "dreinblickenden": "looking",
	  "werkzeugherstellung": "instrument creation",
	  "abgeschaut": "peep, copied",
	  "knurrend": "growling",
	  "gefletschten": "bared",
	  "vormachtstellung": "supremacy",
	  "währenddessen": "meanwhile",
	  "trubel": "hustle",
	  "streift": "walks",
	  "stritten": "argued",
	  "nachwuchs": "offsprings",
	  "zogen": "pulled",
	  "erfanden": "invent",
	  "ahnen": "suspect",
	  "spalten": "split",
	  "unauffällige": "unremarkable",
	  "libellen": "dragonflies",
	  "quallen": "jellyfish",
	  "lebewesen": "creatures",
	  "fortpflanzungsfähige": "reproductive-able",
	  "vorfahren": "ancestors",
	  "fortpflanzung": "reproduction",
	  "maultiere": "mules",
	  "unfruchtbar": "barren",
	  "erheblich": "considerable",
	  "zeugen": "testify; beget",
	  "gattungen": "genera",
	  "gattung": "genus",
	  "zweiteilige": "two-part",
	  "art": "kind",
	  "urahn": "ancestor",
	  "zahmsten": "tamest",
	  "katzenvorfahren": "cat ansectors",
	  "scheinbar": "seemingly",
	  "bestgehüteten": "best-kept",
	  "waisenkind": "orphan",
	  "vettern": "cousins",
	  "krawalligen": "rowdy",
	  "menschenaffen": "great apes",
	  "verwandten": "relatives",
	  "allernächsten": "very next",
	  "urahnin": "ancestral mother",
	  "geschichte": "history",
	  "menschheit": "humankind",
	  "unauffälliges": "unremarkable"
	},
	"ru": {
	  "urknall": "Большой Взрыв",
	  "verbanden": "связали",
	  "namens": "под названием",
	  "entstanden": "появились",
	  "ereignis": "событие",
	  "grundlegenden": "основополагающий",
	  "eigenschaften": "характеристики",
	  "wiederum": "в свою очередь",
	  "zusammenschlossen": "соединились",
	  "bestimmte": "определённая",
	  "bezeichnen": "описывать",
	  "aufbau": "строительство",
	  "entwicklung": "развитие",
	  "geprägt": "сформированный",
	  "beschleunigte": "ускорил",
	  "mitlebewesen": "братья наши меньшие",
	  "menschenähnlichen": "человекоподобные",
	  "stachen": "ужалили",
	  "vielzahl": "разнообразие",
	  "vermutlich": "якобы, предположительно",
	  "äußerlich": "внешне",
	  "gewisse": "определённая",
	  "matsch": "грязь; азарт",
	  "geräusch": "шум",
	  "dreinblickenden": "смотрящий",
	  "werkzeugherstellung": "создание инструментов",
	  "abgeschaut": "подглядел, скопировал",
	  "knurrend": "рычащий",
	  "gefletschten": "обнажённый",
	  "vormachtstellung": "превосходство",
	  "währenddessen": "тем временем",
	  "trubel": "суета",
	  "streift": "прогуливается",
	  "stritten": "спорили",
	  "nachwuchs": "потомки",
	  "zogen": "тянули",
	  "erfanden": "изобретали",
	  "ahnen": "подозревать",
	  "spalten": "расщеплять",
	  "unauffällige": "непримечательный",
	  "libellen": "стрекозы",
	  "quallen": "медузы",
	  "lebewesen": "формы жизни",
	  "fortpflanzungsfähige": "плодородные",
	  "vorfahren": "предки",
	  "fortpflanzung": "размножение",
	  "maultiere": "мулы",
	  "unfruchtbar": "бесплодный",
	  "erheblich": "значительно",
	  "zeugen": "свидетельствовать; зачинать",
	  "gattungen": "рода",
	  "gattung": "род",
	  "zweiteilige": "двухчастный",
	  "art": "вид",
	  "urahn": "предок",
	  "zahmsten": "наиболее приручённый",
	  "katzenvorfahren": "предки кошек",
	  "scheinbar": "кажущийся, по-видимому",
	  "bestgehüteten": "наиболее оберегаемый",
	  "waisenkind": "сирота",
	  "vettern": "кузены",
	  "krawalligen": "хулиганистые",
	  "menschenaffen": "человекоподобные обезьяны",
	  "verwandten": "родственники",
	  "allernächsten": "самые ближние; совсем рядом",
	  "urahnin": "прародительница",
	  "geschichte": "история",
	  "menschheit": "человечество",
	  "unauffälliges": "неприметный"
	}
  }

export const translations = JSON.parse(localStorage.getItem('translations')) || defaultDict
export const translate = (dict, key) => {
	return dict[key.toLowerCase()]
}

export const setTranslation = (lang, original, translation) => {
	translations[lang][original.toLocaleLowerCase()] = translation
	localStorage.setItem('translations', JSON.stringify(translations))
}