const defaultDict = {
	"en": {
		"abgeschaut": "подглядел, скопировал",
		"ahnen": "подозревать",
		"allernächsten": "самые ближние; совсем рядом",
		"angepasst": "адаптировавшийся",
		"anspruch": "притязание, претензия",
		"art": "вид",
		"aufbau": "строительство",
		"ausgrabungen": "раскопки",
		"auswanderergruppen": "группы переселенцев",
		"beschleunigte": "ускорил",
		"bestgehüteten": "наиболее оберегаемый",
		"bestimmte": "определённая",
		"bewahrt": "сохранён",
		"bezeichnen": "описывать",
		"dreinblickenden": "смотрящий",
		"ebenfalls": "также, равным образом",
		"eigenschaften": "характеристики",
		"eingestellt": "приспособленный",
		"entstanden": "появились",
		"entwickelten": "развили",
		"entwicklung": "развитие",
		"ereignis": "событие",
		"erfanden": "изобретали",
		"ergaben": "дали результат",
		"ergebnis": "результат",
		"erheblich": "значительно",
		"feige": "трусливые",
		"fortpflanzung": "размножение",
		"fortpflanzungsfähige": "плодородные",
		"fähigkeiten": "навыки",
		"gattung": "род",
		"gattungen": "рода",
		"gefletschten": "обнажённый",
		"gehütet": "сберёг",
		"geprägt": "сформированный",
		"geräusch": "шум",
		"geschichte": "история",
		"getauft": "окрещён",
		"gewisse": "определённая",
		"grundlegenden": "основополагающий",
		"hervorging": "появился",
		"hochtrabend": "грандиозный, помпезный",
		"jedoch": "тем не менее",
		"katzenvorfahren": "предки кошек",
		"keller": "погреб",
		"knurrend": "рычащий",
		"krawalligen": "хулиганистые",
		"lebewesen": "формы жизни",
		"leichen": "трупы",
		"libellen": "стрекозы",
		"matsch": "грязь; азарт",
		"maultiere": "мулы",
		"menschenaffen": "человекоподобные обезьяны",
		"menschenähnlichen": "человекоподобные",
		"menschheit": "человечество",
		"mitlebewesen": "братья наши меньшие",
		"nachwuchs": "потомки",
		"namens": "под названием",
		"quallen": "медузы",
		"reihe": "ряд",
		"richtungen": "направления",
		"salopp": "небрежно, грубовато",
		"scheinbar": "кажущийся, по-видимому",
		"schwülen": "знойный",
		"spalten": "расщеплять",
		"speerschwingenden": "вооружённые копьями",
		"stachen": "ужалили",
		"stießen": "наткнулись",
		"streift": "прогуливается",
		"stritten": "спорили",
		"trubel": "суета",
		"unauffällige": "непримечательный",
		"unauffälliges": "неприметный",
		"unfruchtbar": "бесплодный",
		"urahn": "предок",
		"urahnin": "прародительница",
		"urknall": "Большой Взрыв",
		"verbanden": "связали",
		"vermutlich": "якобы, предположительно",
		"verschneiten": "заснеженный",
		"versteinerten": "окаменелые",
		"verwandten": "родственники",
		"vettern": "кузены",
		"vielzahl": "разнообразие",
		"vorfahren": "предки",
		"vormachtstellung": "превосходство",
		"waisenkind": "сирота",
		"werkzeugherstellung": "создание инструментов",
		"wiederum": "в свою очередь",
		"währenddessen": "тем временем",
		"zahmsten": "наиболее приручённый",
		"zeugen": "свидетельствовать; зачинать",
		"zogen": "тянули",
		"zusammenschlossen": "соединились",
		"zweiteilige": "двухчастный",
		"äußerlich": "внешне"
	},
	"ru": {
		"abgeschaut": "подглядел, скопировал",
		"ahnen": "подозревать",
		"allernächsten": "самые ближние; совсем рядом",
		"angepasst": "адаптировавшийся",
		"anspruch": "притязание, претензия",
		"art": "вид",
		"aufbau": "строительство",
		"ausgrabungen": "раскопки",
		"auswanderergruppen": "группы переселенцев",
		"beschleunigte": "ускорил",
		"bestgehüteten": "наиболее оберегаемый",
		"bestimmte": "определённая",
		"bewahrt": "сохранён",
		"bezeichnen": "описывать",
		"dreinblickenden": "смотрящий",
		"ebenfalls": "также, равным образом",
		"eigenschaften": "характеристики",
		"eingestellt": "приспособленный",
		"entstanden": "появились",
		"entwickelten": "развили",
		"entwicklung": "развитие",
		"ereignis": "событие",
		"erfanden": "изобретали",
		"ergaben": "дали результат",
		"ergebnis": "результат",
		"erheblich": "значительно",
		"feige": "трусливые",
		"fortpflanzung": "размножение",
		"fortpflanzungsfähige": "плодородные",
		"fähigkeiten": "навыки",
		"gattung": "род",
		"gattungen": "рода",
		"gefletschten": "обнажённый",
		"gehütet": "сберёг",
		"geprägt": "сформированный",
		"geräusch": "шум",
		"geschichte": "история",
		"getauft": "окрещён",
		"gewisse": "определённая",
		"grundlegenden": "основополагающий",
		"hervorging": "появился",
		"hochtrabend": "грандиозный, помпезный",
		"jedoch": "тем не менее",
		"katzenvorfahren": "предки кошек",
		"keller": "погреб",
		"knurrend": "рычащий",
		"krawalligen": "хулиганистые",
		"lebewesen": "формы жизни",
		"leichen": "трупы",
		"libellen": "стрекозы",
		"matsch": "грязь; азарт",
		"maultiere": "мулы",
		"menschenaffen": "человекоподобные обезьяны",
		"menschenähnlichen": "человекоподобные",
		"menschheit": "человечество",
		"mitlebewesen": "братья наши меньшие",
		"nachwuchs": "потомки",
		"namens": "под названием",
		"quallen": "медузы",
		"reihe": "ряд",
		"richtungen": "направления",
		"salopp": "небрежно, грубовато",
		"scheinbar": "кажущийся, по-видимому",
		"schwülen": "знойный",
		"spalten": "расщеплять",
		"speerschwingenden": "вооружённые копьями",
		"stachen": "ужалили",
		"stießen": "наткнулись",
		"streift": "прогуливается",
		"stritten": "спорили",
		"trubel": "суета",
		"unauffällige": "непримечательный",
		"unauffälliges": "неприметный",
		"unfruchtbar": "бесплодный",
		"urahn": "предок",
		"urahnin": "прародительница",
		"urknall": "Большой Взрыв",
		"verbanden": "связали",
		"vermutlich": "якобы, предположительно",
		"verschneiten": "заснеженный",
		"versteinerten": "окаменелые",
		"verwandten": "родственники",
		"vettern": "кузены",
		"vielzahl": "разнообразие",
		"vorfahren": "предки",
		"vormachtstellung": "превосходство",
		"waisenkind": "сирота",
		"werkzeugherstellung": "создание инструментов",
		"wiederum": "в свою очередь",
		"währenddessen": "тем временем",
		"zahmsten": "наиболее приручённый",
		"zeugen": "свидетельствовать; зачинать",
		"zogen": "тянули",
		"zusammenschlossen": "соединились",
		"zweiteilige": "двухчастный",
		"äußerlich": "внешне"
	}
}

export const translations = JSON.parse(localStorage.getItem('translations')) || defaultDict
export const translate = (dict, key) => {
	return dict[key.toLowerCase()]
}

export const setTranslation = (lang, original, translation) => {
	translations[lang][original.toLocaleLowerCase()] = translation
	localStorage.setItem('translations', JSON.stringify(translations))
}

export const requestLocalTranslation = (word) => {
	fetch(`/local-dictionary/${word.toLocaleLowerCase()}.json`)
		.then((response) => {
			if (response.ok) {
				return response.json()
			} else {
				throw new Error('Network response was not OK', response)
			}
		})
		.then(console.log.bind(console))
	.catch(response => console.log('no local dict entry', response))
}