export const text =
`Kapitel 1
Ein ziemlich unauffälliges Tier
Vor rund 13,5 Milliarden Jahren entstanden Materie, Energie, Raum und Zeit in einem Ereignis namens Urknall. Die Geschichte dieser grundlegenden Eigenschaften unseres Universums nennen wir Physik.
Etwa 300000 Jahre später verbanden sich Materie und Energie zu komplexeren Strukturen namens Atome, die sich wiederum zu Molekülen zusammenschlossen. Die Geschichte der Atome, Moleküle und ihrer Reaktionen nennen wir Chemie.
Vor 3,8 Milliarden Jahren begannen auf einem Planeten namens Erde bestimmte Moleküle, sich zu besonders großen und komplexen Strukturen zu verbinden, die wir als Organismen bezeichnen. Die Geschichte dieser Organismen nennen wir Biologie.
Und vor gut 70000 Jahren begannen Organismen der Art Homo sapiens mit dem Aufbau von noch komplexeren Strukturen namens Kulturen. Die Entwicklung dieser Kulturen nennen wir Geschichte.
Die Geschichte der menschlichen Kulturen wurde von drei großen Revolutionen geprägt. Die kognitive Revolution vor etwa 70000 Jahren brachte die Geschichte überhaupt erst in Gang. Die landwirtschaftliche Revolution vor rund 12000 Jahren beschleunigte sie. Und die wissenschaftliche Revolution, die vor knapp 500 Jahren ihren Anfang nahm, könnte das Ende der Geschichte und der Beginn von etwas völlig Neuem sein. Dieses Buch erzählt, welche Konsequenzen diese drei Revolutionen für den Menschen und seine Mitlebewesen hatten und haben.
Menschen gab es schon lange vor dem Beginn der Geschichte. Die ersten menschenähnlichen Tiere betraten vor etwa 2,5 Millionen Jahren die Bühne. Aber über zahllose Generationen hinweg stachen sie nicht aus der Vielzahl der Tiere heraus, mit denen sie ihren Lebensraum teilten. Wenn wir 2 Millionen Jahre in die Vergangenheit reisen und einen Spaziergang durch Ostafrika unternehmen könnten, würden wir dort vermutlich Gruppen von Menschen begegnen, die äußerlich gewisse Ähnlichkeit mit uns haben. Besorgte Mütter tragen ihre Babys auf dem Arm, Kinder spielen im Matsch. Von irgendwoher dringt das Geräusch von Steinen, die aufeinandergeschlagen werden, und wir sehen einen ernst dreinblickenden jungen Mann, der sich in der Kunst der Werkzeugherstellung übt. Die Technik hat er sich bei zwei Männern abgeschaut, die sich gerade um einen besonders fein gearbeiteten Feuerstein streiten; knurrend und mit gefletschten Zähnen tragen sie eine weitere Runde im Kampf um die Vormachtstellung in der Gruppe aus. Währenddessen zieht sich ein älterer Herr mit weißen Haaren aus dem Trubel zurück und streift allein durch ein nahe gelegenes Waldstück, wo er von einer Horde Schimpansen überrascht wird.
Diese Menschen liebten, stritten, zogen ihren Nachwuchs auf und erfanden Werkzeuge – genau wie die Schimpansen. Niemand, schon gar nicht die Menschen selbst, konnte ahnen, dass ihre Nachfahren eines Tages über den Mond spazieren, Atome spalten, das Genom entschlüsseln oder Geschichtsbücher schreiben würden. Die prähistorischen Menschen waren unauffällige Tiere, die genauso viel oder so wenig Einfluss auf ihre Umwelt hatten wie Gorillas, Libellen oder Quallen.
Biologen teilen Lebewesen in verschiedene Arten ein. Tiere gehören derselben Art an, wenn sie sich miteinander paaren und fortpflanzungsfähige Nachkommen zeugen. Pferde und Esel haben einen gemeinsamen Vorfahren und viele gemeinsame Eigenschaften, doch was die Fortpflanzung angeht, haben sie kein Interesse aneinander. Man kann sie zwar dazu bringen, sich zu paaren, doch die Maultiere, die aus dieser Verbindung hervorgehen, sind unfruchtbar. Das ist ein Zeichen dafür, dass sie unterschiedlichen Arten angehören. Anders Bulldoggen und Cockerspaniel: Sie unterscheiden sich zwar äußerlich ganz erheblich, doch sie paaren sich sehr bereitwillig, und ihr Nachwuchs kann mit anderen Hunden neue Welpen zeugen. Bulldoggen und Cockerspaniel sind also Angehörige derselben Art, nämlich der Hunde.
Arten mit einem gemeinsamen Vorfahren werden oft zu Gattungen zusammengefasst. Löwen, Tiger, Leoparden und Jaguare sind beispielsweise unterschiedliche Arten der Gattung Panthera. Biologen geben Lebewesen zweiteilige lateinische Namen: der erste Teil bezeichnet die Gattung, der zweite die Art. Der Löwe heißt zum Beispiel Panthera leo: die Art Leo aus der Gattung der Panthera. Als Leser dieses Buchs gehören Sie vermutlich den Homo sapiens an – der Art Sapiens (weise) aus der Gattung Homo (Mensch).
Gattungen werden wiederum zu Familien zusammengefasst, zum Beispiel den Katzen (Löwen, Geparden, Hauskatzen), Hunden (Wölfe, Füchse, Schakale) oder Elefanten (Elefanten, Mammuts, Mastodonten). Alle Angehörigen einer Familie lassen sich auf einen gemeinsamen Urahn zurückführen. Alle Katzen, vom zahmsten Hauskätzchen zum wildesten Löwen, gehen auf einen gemeinsamen Katzenvorfahren zurück, der vor rund 25 Millionen Jahren lebte.
Natürlich gehört auch der Homo sapiens einer Familie an. Diese scheinbar so banale Tatsache war eines der bestgehüteten Geheimnisse der Geschichte. Der Homo sapiens tat nämlich lange so, als habe er nichts mit dem Rest der Tierwelt zu tun und sei ein Waisenkind ohne Geschwister und Vettern und vor allem ohne Eltern. Das ist natürlich nicht der Fall. Ob es uns gefällt oder nicht, wir gehören der großen und krawalligen Familie der Menschenaffen an. Unsere nächsten lebenden Verwandten sind Gorillas und Orang-Utans. Am allernächsten stehen uns jedoch die Schimpansen. Vor gerade einmal sechs Millionen Jahren brachte eine Äffin zwei Töchter zur Welt: Eine der beiden wurde die Urahnin aller Schimpansen, die andere ist unsere eigene Ur-Ur-Ur-Großmutter.`

export default text